// Code generated by stringdata. DO NOT EDIT.

package schema

// BitbucketServerSchemaJSON is the content of the file "bitbucket_server.schema.json".
const BitbucketServerSchemaJSON = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "bitbucket_server.schema.json#",
  "title": "BitbucketServerConnection",
  "description": "Configuration for a connection to Bitbucket Server.",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "username",
    "url",
    "repositoryQuery"
  ],
  "oneOf": [
    {
      "required": [
        "token"
      ],
      "properties": {
        "password": {
          "type": "null"
        }
      }
    },
    {
      "required": [
        "password"
      ],
      "properties": {
        "token": {
          "type": "null"
        }
      }
    }
  ]
}
`
