// Code generated by stringdata. DO NOT EDIT.

package schema

// GitLabSchemaJSON is the content of the file "gitlab.schema.json".
const GitLabSchemaJSON = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "gitlab.schema.json#",
  "title": "GitLabConnection",
  "description": "Configuration for a connection to GitLab (GitLab.com or GitLab self-managed).",
  "type": "object",
  "additionalProperties": false,
  "required": ["url", "token", "projectQuery"]
}
`
