// Code generated by stringdata. DO NOT EDIT.

package schema

// GitoliteSchemaJSON is the content of the file "gitolite.schema.json".
const GitoliteSchemaJSON = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "gitolite.schema.json#",
  "title": "GitoliteConnection",
  "description": "Configuration for a connection to Gitolite.",
  "type": "object",
  "additionalProperties": false,
  "required": ["prefix", "host"]
}
`
