// Code generated by stringdata. DO NOT EDIT.

package schema

// OtherExternalServiceSchemaJSON is the content of the file "other_external_service.schema.json".
const OtherExternalServiceSchemaJSON = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "other_external_service.schema.json#",
  "title": "OtherExternalServiceConnection",
  "description": "Configuration for a Connection to Git repositories for which an external service integration isn't yet available.",
  "type": "object",
  "additionalProperties": false,
  "required": ["repos"]
}
`
