// Code generated by go-jsonschema-compiler. DO NOT EDIT.

package schema

// AWSCodeCommitConnection description: Configuration for a connection to AWS CodeCommit.
type AWSCodeCommitConnection struct {
	Region interface{} `json:"region"`
}
